apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aqf5pk4fa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aqf5pk4fa-python 
  name: aqf5pk4fa-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aqf5pk4fa-python
    weight: 100 
